version: '3.4'

services:
  mongo_db:
    image: mongo
    volumes:
      - mongodb:/var/lib/mongo

  cars-service:
    build:
      context: .
      dockerfile: ./cars_microservice/Dockerfile
    #ports:
    #  - "2227"
    #  - "2227:2227"
    restart: always
    env_file:
      - car.env
      - commons.env

volumes:
  mongodb: