apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-service
spec:
  ports:
    - name: plaintext
      port: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  #type: NodePort
  ports:
    - port: 2181
      targetPort: 2181
      name: zoo-port
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  type: NodePort
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
  selector:
    db: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
  labels:
    name: logging-service
spec:
  type: NodePort
  ports:
    - port: 2224
      targetPort: 2224
      name: logging-port
  selector:
      service: logging
---
apiVersion: v1
kind: Service
metadata:
  name: rentals-service
  labels:
    name: rentals-service
spec:
  type: NodePort
  ports:
    - port: 2223
      targetPort: 2223
      name: rentals-api-port
  selector:
    service: rentals
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  labels:
    name: payments-service
spec:
  type: NodePort
  ports:
    - port: 2222
      targetPort: 2222
      name: payments-api-port
  selector:
    service: payments
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 2221
      targetPort: 2221
      name: gateway-port
  selector:
    service: gateway
