apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoices-dp
spec:
  selector:
    matchLabels:
      service: invoices
  template:
    metadata:
      name: invoices-pod
      labels:
        service: invoices
    spec:
      containers:
        - name: invoices-cnt
          image: carsharing_invoices-service
          imagePullPolicy: "Never"
          ports:
            - containerPort: 2226
              name: invoices-port
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-auth-secret
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-auth-secret
                  key: password
          envFrom:
            - configMapRef:
                name: invoices-config
            - configMapRef:
                name: common-config
          #startupProbe:
          #  httpGet:
          #    path: /invoice/ping
          #    port: 2226
          #  failureThreshold: 30
          #  periodSeconds: 10
          #readinessProbe:
          #  httpGet:
          #    path: /invoice/ping
          #    port: 2226
          #  initialDelaySeconds: 20
          #  failureThreshold: 5
          #  periodSeconds: 5
          #livenessProbe:
          #  httpGet:
          #    path: /invoice/ping
          #    port: 2226
          #  initialDelaySeconds: 20
          #  failureThreshold: 5
          #  periodSeconds: 5

